### ISSUE TITLE
Game is too much fun

### ISSUE THREAD

**Issue by basicallydan** [git-game/git-game#4]
I have work to do, @hgarc014, and your game is distracting me.

**Comment by BSanchez** [comment]
same here, you are an evil person @hgarc014

**Comment by kamalbanga** [comment]
@basicallydan I think this game is rather good for work, especially since it's just 30 minutes and it rather boosts enthusiasm.

**Comment by hgarc014** [comment]
haha, well, I'm glad people are taking a liking to this.

**Comment by qaisermazhar** [comment]
When it comes to issues on projects, I could live with this ;) nice work hgarc014!

**Comment by djouuuuh** [comment]
Had a lot of fun here too. Thanks for this moment @hgarc014 ;)

**Comment by Dalker** [comment]
Thanks for this game, @hgarc014 , that helped me get back to git (after a long break on mercurial...)

**Comment by FireAlkazar** [comment]
Great job! So much fun:)

**Comment by lks** [comment]
I agree, with my team, we test your game on the lunch time and it was a very great moment.
Thanks @hgarc014!

**Comment by hgarc014** [comment]
glad everyone has enjoyed it =)
