### ISSUE TITLE
Game is too short!

### ISSUE THREAD

**Issue by mriehl** [git-game/git-game#5]
Would you like to share (blog?) how you managed to put this together without going crazy?
Is it kinda automated or did you do everything manually?
I was secretly hoping for an occasion to use git bisect for example.

Making a puzzle game out of it is an awesome idea for learning and it would be great to be able to extend this.

**Comment by hgarc014** [comment]
Yeah, I can attempt to write something. I didn't do all of this by myself @drami025 helped greatly. 

Extending the game will most likely come in the future. We would have to think of more ideas and collaborate further.

**Comment by 2c2c** [comment]
this was a 'do something to help the world' assignment for a class with pretty short deadline

I dropped by seeing this now had 600 stars. wowie. you probably have free manpower to get this extended to cover just about any feature you want. good luck
